name: dependencies
description: A simple and modular dependency injection system without using reflection.
version: 0.1.5
homepage: https://github.com/marcguilera/dependencies.dart
author: marcguilera <marcguilerap@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  quiver: ^3.0.1+1
  disposables: ^1.0.0

dev_dependencies:
  test: ^1.19.3
